import '../styles/globals.css'
import Head from 'next/head';
import NavBar from '../components/molecules/NavBar';
import Footer from '../components/molecules/Footer';

function MyApp({ Component, pageProps }) {
  return <>
  <Head>
    <title>Iberê Abondanza Kuhlmann</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <NavBar />
  <Component {...pageProps}  />
  <Footer />
</>
}

export default MyApp
