import React from 'react';
import Head from 'next/head'


export default function about() {
  return (
    <>
      <Head>
        <title>About Iberê Abondanza Kuhlmann</title>
        <meta name="Page with bio description from Iberê Abondanza Kuhlmann" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>Iberê Abondanza Kuhlmann</h2>

        <h3>Fullstack developer</h3>
        <p>
          Desenvolvedor FrontEnd e BackEnd apaixonado por lógica de programação.
        </p>
        <h3>Bio</h3>
        <p>
          Lorem Ipsus
        </p>
        <h3>Skills</h3>
        <span>React.Js </span>
        <span>Node.Js </span>
        <span>Next.Js </span>
      </main>
    </>
  )
}
