import React from 'react';
import Head from 'next/head'
import ContactIcons from '../components/molecules/ContactIcons'

export default function contact() {
  return (
    <>
      <Head>
        <title>Contact to Iberê Abondanza Kuhlmann</title>
        <meta name="Page with contact with Iberê Abondanza Kuhlmann" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Contact me</p>
        <p>English, Portuguese or Italian</p>
        <ContactIcons withLabel />
      </main>
    </>
  )
}
